language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1

codecov: true

after_success:
- julia -e 'cd(Pkg.dir("Mozi")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'